server.port=8092
server.forward-headers-strategy=framework

xoai.config.path=config/xoai.config
solr.url=http://localhost:8983/solr/oai

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
