server.port=8092
server.forward-headers-strategy=framework

xoai.config.path=config/application.properties.model

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
